# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waitup < Formula
  desc "A tool to monitor system availability via RDP or SSH"
  homepage "https://github.com/creaked/waitup"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_macOS_x86_64.tar.gz"
      sha256 "514d9f662722e128298072754e47e1d37d9f23d3329e189db40b6f3ae2a81d06"

      def install
        bin.install "waitup"
      end
    end
    on_arm do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_macOS_arm64.tar.gz"
      sha256 "2b89186b25b8c4e3cad43fc622c4d7f4bf7abf9e60a951733f7374992a89f255"

      def install
        bin.install "waitup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_x86_64.tar.gz"
        sha256 "c563076e230d49131c693a5bfed010698a8e143d774df3a81be24f08d3df82a8"

        def install
          bin.install "waitup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_arm64.tar.gz"
        sha256 "673bc3a5373d7dcd9b3c5c9690c2ac23689f9582bf7e75e80ab8e62f33b3fe3b"

        def install
          bin.install "waitup"
        end
      end
    end
  end
end
