# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waitup < Formula
  desc "A tool to monitor system availability via RDP or SSH"
  homepage "https://github.com/creaked/waitup"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Darwin_x86_64.tar.gz"
      sha256 "b7abc645ea5bfc07a999197ea5a0003094bf908646094a792f8f7be1ae1ab5bc"

      def install
        bin.install "waitup"
      end
    end
    on_arm do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Darwin_arm64.tar.gz"
      sha256 "141b2319eef70fb615aa7b301f4a5ece2746f4d5d5e6f3fe1a5b58e4b049b703"

      def install
        bin.install "waitup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_x86_64.tar.gz"
        sha256 "4ef6781179685ef582bedaa3f6dc9783173ec0f8a91e4f0bbcd7e16ab4b617bd"

        def install
          bin.install "waitup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_arm64.tar.gz"
        sha256 "05c6639811bcbd797ccc84efe4e66d6766b3ed248cce0c84cbb5441d44a7c0ad"

        def install
          bin.install "waitup"
        end
      end
    end
  end
end
