# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waitup < Formula
  desc "A tool to monitor system availability via RDP or SSH"
  homepage "https://github.com/creaked/waitup"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_macOS_x86_64.tar.gz"
      sha256 "50cd226975ef2138ff61a0c96a0bcf26fb648f31c140ebe020dc2198dcf9cff5"

      def install
        bin.install "waitup"
      end
    end
    on_arm do
      url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_macOS_arm64.tar.gz"
      sha256 "cc96dba521263914ed3e0392752863c7b25815ec25999725c586272964f6adc5"

      def install
        bin.install "waitup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_x86_64.tar.gz"
        sha256 "6425e3d17bd7e69e81da75d981c0c9a769bcec0d142ae069bbf74cc6b508af17"

        def install
          bin.install "waitup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creaked/waitup/releases/download/v0.3.0/waitup_Linux_arm64.tar.gz"
        sha256 "f5ffb5e26e78e58d27ea95792780058579b9cf73b21367a2a99a3bfae1a54fe3"

        def install
          bin.install "waitup"
        end
      end
    end
  end
end
